version: '2'
services:
  nginx:
    build:
      context: ./nginx/
    volumes:
      - wwwdata:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - phpfpm
  phpfpm:
    build:
      context: ./phpfpm/
    volumes:
      - wwwdata:/var/www/html
    ports:
      - "9000:9000"
  phptest:
    build:
      context: ./phptest/
    volumes:
      - wwwdata:/var/www/html
    depends_on:
      - phpfpm
volumes:
  wwwdata:

