version: '2'
services:
  nginx:
    build:
      context: ./nginx/
    volumes:
      - wwwdata:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm/
    volumes:
      - wwwdata:/var/www/html
    ports:
      - "9000:9000"
volumes:
  wwwdata:

